/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.p2oyun;

import java.awt.FlowLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Random;







/**
 *
 * @author hp
 */
public class P2Oyun extends javax.swing.JFrame {
    
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(P2Oyun.class.getName());
   String seciliKelime = "";
   String kelimelerDosyaAdi = "C:\\P2Oyun\\TXTDosyalar\\kelimeler.txt";
   String oyunlarDosyaAdi = "C:\\P2Oyun\\TXTDosyalar\\oyunlar.txt";
   String resimlerDosyaAdi = "C:\\P2Oyun\\Resimler\\";
   String sifreDosyaAdi = "C:\\P2Oyun\\TXTDosyalar\\sifre.txt";
   String logDosyaAdi = "C:\\P2Oyun\\TXTDosyalar\\log.txt";
   int yanlisTahmin=0;
   int sure = 0;
   Timer timer;
   int resimIndex = 1;
   

    /**
     * Creates new form P2Oyun
     */
    public P2Oyun() {
        initComponents();
        
         this.setVisible(false);
         SifreEkrani sifreEkrani = new SifreEkrani(this);
         sifreEkrani.setVisible(true);
         jTabbedPane2.setEnabledAt(2, false); 
         jTextField1.setText("");
         jTextField2.setText("");
         skorlariYukle();
         loglariYukle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        harfPaneli = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("TEMİZLE");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eski Skorlar", jPanel4);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton4.setText("TEMİZLE");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton4)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Loglar", jPanel5);

        jLabel1.setText("Harf Tahmini :");

        jTextField1.setText("jTextField1");

        jButton1.setText("Tahmin Et");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel2.setText("Kelime Tahmini :");

        jTextField2.setText("jTextField2");

        jButton2.setText("Tahmin Et");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel3.setText("Süre:");

        jLabel4.setText("                ...");

        javax.swing.GroupLayout harfPaneliLayout = new javax.swing.GroupLayout(harfPaneli);
        harfPaneli.setLayout(harfPaneliLayout);
        harfPaneliLayout.setHorizontalGroup(
            harfPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        harfPaneliLayout.setVerticalGroup(
            harfPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(harfPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(harfPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Oyun Oynama", jPanel3);

        jMenu1.setText("OYUN MENÜSÜ");

        jMenuItem1.setText("Oyuna Başla");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Oyunu Yeniden Başlat");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Çıkış");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oyunuBaslat() {
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jTabbedPane2.setEnabledAt(2, true);
        resimIndex = 1;
        jLabel4.setIcon(null);
    try {
         List<String> liste = Files.readAllLines(new File(kelimelerDosyaAdi).toPath(), Charset.defaultCharset());
        
        Random random = new Random();
        seciliKelime = liste.get(random.nextInt(liste.size())).toUpperCase().trim();
        
        int harfSayisi = seciliKelime.length();
        
        harfPaneli.removeAll();
        harfPaneli.setLayout(new FlowLayout(java.awt.FlowLayout.LEFT, 5, 5));
        
        for (int i = 0; i < harfSayisi; i++) {
            JLabel lbl = new JLabel("*");
            lbl.setName("lbl" + i);
            harfPaneli.add(lbl);
        }
        
        harfPaneli.revalidate();
        harfPaneli.repaint();
        
        yanlisTahmin = 0;
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Hata: " + e.getMessage());
    }
    
    if (timer != null) {
    timer.stop();
    }
    sure = 0;
    jLabel3.setText("Süre: 0");
    
    timer = new Timer(1000, e -> {
            sure++;
            jLabel3.setText("Süre: " + sure);
        });
        timer.start();
        
        skorlariYukle();
        loglariYukle();
}
    
    private void resimGoster() {
    String yol = resimlerDosyaAdi + resimIndex + ".jpg";
    ImageIcon icon = new ImageIcon(yol);
    Image img = icon.getImage();
    Image scaled = img.getScaledInstance(125, 125, Image.SCALE_SMOOTH);
    jLabel4.setIcon(new ImageIcon(scaled));
    jLabel4.setText("");
    resimIndex++;
}
    
    private void oyunuKaydet(String sonuc) {
    try {
        String zaman = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss").format(new Date());
        String satir = zaman + " - Süre: " + sure + " saniye - Sonuç: " + sonuc + "\n";
        
        FileWriter yaz = new FileWriter(oyunlarDosyaAdi, true);
        yaz.write(satir);
        yaz.close();
        
        skorlariYukle();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Kayıt hatası: " + e.getMessage());
    }
}
    
    private void skorlariYukle() {
    try {
         List<String> liste = Files.readAllLines(new File(oyunlarDosyaAdi).toPath(), Charset.defaultCharset());
        
        String[] sutunlar = {"Tarih", "Süre", "Sonuç"};
        DefaultTableModel model = new DefaultTableModel(null, sutunlar);
        
        for (String satir : liste) {
            if (!satir.isEmpty()) {
                String[] parcalar = satir.split(" - ");
                if (parcalar.length >= 3) {
                    model.addRow(new Object[]{parcalar[0], parcalar[1], parcalar[2]});
                }
            }
        }
        
        jTable1.setModel(model);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Hata: " + e.getMessage());
    }
}
    
    public void loglariYukle() {
    try {
        List<String> liste = Files.readAllLines(new File(logDosyaAdi).toPath(), Charset.defaultCharset());
        
        String[] sutunlar = {"Tarih", "İşlem"};
        DefaultTableModel model = new DefaultTableModel(null, sutunlar);
        
        for (String satir : liste) {
            if (!satir.isEmpty()) {
                String[] parcalar = satir.split(" - ");
                if (parcalar.length >= 2) {
                    model.addRow(new Object[]{parcalar[1], parcalar[0]});
                }
            }
        }
        
        jTable2.setModel(model);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Hata: " + e.getMessage());
    }
}
       
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         oyunuBaslat();
         jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String tahmin = jTextField2.getText().trim();
        
        if (tahmin.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Lütfen bir kelime girin!");
        return;
    }
    
    if (tahmin.toUpperCase().equals(seciliKelime.toUpperCase())) {
        timer.stop();
        oyunuKaydet("KAZANDI");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);

        for (int i = 0; i < harfPaneli.getComponentCount(); i++) {
            JLabel siradakiLabel = (JLabel) harfPaneli.getComponent(i);
            siradakiLabel.setText(String.valueOf(seciliKelime.charAt(i)));
        }
        JOptionPane.showMessageDialog(this, "Tebrikler! Kelimeyi buldunuz");
    } else {
        yanlisTahmin++;
        resimGoster();
        if (yanlisTahmin >= 11) {
            timer.stop();
            oyunuKaydet("KAYBETTİ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            
            for (int i = 0; i < harfPaneli.getComponentCount(); i++) {
            JLabel siradakiLabel = (JLabel) harfPaneli.getComponent(i);
            siradakiLabel.setText(String.valueOf(seciliKelime.charAt(i)));
         }
        JOptionPane.showMessageDialog(this, "Oyunu kaybettiniz! Kelime: " + seciliKelime);
    } else {
        JOptionPane.showMessageDialog(this, "Kelimeyi yanlış tahmin ettiniz! Kalan hakkınız: " + (11 - yanlisTahmin));
    }
    }
    
    jTextField2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tahmin = jTextField1.getText().trim();
        
         if (tahmin.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Lütfen bir harf girin!");
        return;
    }
    
    if (tahmin.length() != 1) {
        JOptionPane.showMessageDialog(this, "Lütfen tek harf girin!");
        return;
    }
    
        boolean bulundu = false;
    
    for (int i = 0; i < harfPaneli.getComponentCount(); i++) {
        JLabel siradakiLabel = (JLabel) harfPaneli.getComponent(i);
        
        if (tahmin.toUpperCase().equals(String.valueOf(seciliKelime.toUpperCase().charAt(i)))) {
            siradakiLabel.setText(tahmin.toUpperCase());
            bulundu = true;
        }
    }
    
    if (bulundu == true) {
        JOptionPane.showMessageDialog(this, "Harf bulundu!");
        
        boolean hepsiAcildi = true;
    for (int i = 0; i < harfPaneli.getComponentCount(); i++) {
        JLabel siradakiLabel = (JLabel) harfPaneli.getComponent(i);
        if (siradakiLabel.getText().equals("*")) {
            hepsiAcildi = false;
            break;
        }
    }
    
    if (hepsiAcildi) {
        timer.stop();
        oyunuKaydet("KAZANDI");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Tebrikler! Kelimeyi buldunuz!");
    }
    
    } else {
        yanlisTahmin++;
        resimGoster();
        if (yanlisTahmin >= 11) {
            timer.stop();
            oyunuKaydet("KAYBETTİ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            
             for (int i = 0; i < harfPaneli.getComponentCount(); i++) {
            JLabel siradakiLabel = (JLabel) harfPaneli.getComponent(i);
            siradakiLabel.setText(String.valueOf(seciliKelime.charAt(i)));
         }
            JOptionPane.showMessageDialog(this, "Oyunu kaybettiniz! Kelime: " + seciliKelime);
        } else {
            JOptionPane.showMessageDialog(this, "Harf yok! Kalan hakkınız: " + (11 - yanlisTahmin));
        }
    }
    
    jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         int onay = JOptionPane.showConfirmDialog(this, 
        "Oyunu yeniden başlatmak istiyor musunuz?", 
        "Yeniden Başlat", 
        JOptionPane.YES_NO_OPTION);
    
    if (onay == JOptionPane.YES_OPTION) {
        oyunuBaslat();
    }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String girilen = JOptionPane.showInputDialog(this, "Şifrenizi girin:");
    
    if (girilen != null) {
        try {
            List<String> liste = Files.readAllLines(new File(sifreDosyaAdi).toPath(), Charset.defaultCharset());
            String kayitliSifre = liste.get(0);
            
            if (girilen.equals(kayitliSifre)) {
                FileWriter yaz =new FileWriter(oyunlarDosyaAdi, false);
                yaz.write("");
                yaz.close();
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                JOptionPane.showMessageDialog(this, "Skorlar başarıyla temizlendi.");
            } else {
                JOptionPane.showMessageDialog(this, "Şifrenizi yanlış girdiniz!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Hata: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String girilen = JOptionPane.showInputDialog(this, "Şifreyi girin:");
    
    if (girilen != null) {
        try {
            List<String> liste = Files.readAllLines(new File(sifreDosyaAdi).toPath(), Charset.defaultCharset());
            String kayitliSifre = liste.get(0);
            
            if (girilen.equals(kayitliSifre)) {
                FileWriter yaz = new FileWriter(logDosyaAdi, false);
                yaz.write("");
                yaz.close();
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setRowCount(0);
                JOptionPane.showMessageDialog(this, "Loglar başarıyla temizlendi.");
            } else {
                JOptionPane.showMessageDialog(this, "Şifrenizi yanlış girdiniz!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Hata: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new P2Oyun());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel harfPaneli;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
