/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.p2oyun;

import java.io.File;
import java.io.FileWriter;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class SifreEkrani extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SifreEkrani.class.getName());
    
    String sifreDosyaAdi = "C:\\P2Oyun\\TXTDosyalar\\sifre.txt";
    String logDosyaAdi = "C:\\P2Oyun\\TXTDosyalar\\log.txt";
    int yanlisSayisi=0;
    private P2Oyun anaEkran;

    /**
     * Creates new form SifreEkranı
     */
    public SifreEkrani(P2Oyun anaEkran) {
        initComponents();
        this.anaEkran = anaEkran;
        jPasswordField1.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ŞİFRE :");

        jButton1.setText("GİRİŞ");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logYaz(String etiket) {
        try {
            String zaman = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss").format(new Date());
            String satir = etiket + " - " + zaman + "\n";
            
            FileWriter yaz = new FileWriter(logDosyaAdi, true);
            yaz.write(satir);
            yaz.close();
            
             anaEkran.loglariYukle();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Log hatası: " + e.getMessage());
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Path filePath = new File(sifreDosyaAdi).toPath();
    
    try {
        List<String> stringList = Files.readAllLines(filePath, Charset.defaultCharset());
        
        if (stringList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Şifre Oluşturun");
            
            String yeniSifre = JOptionPane.showInputDialog(this, "Yeni şifrenizi girin:");
            
            if (yeniSifre != null && !yeniSifre.isEmpty()) {
                FileWriter yaz = new FileWriter(sifreDosyaAdi, false);
                yaz.write(yeniSifre);
                yaz.close();
                logYaz("Şifre Oluşturuldu");
                JOptionPane.showMessageDialog(this, "Şifre kaydedildi!");
            }
            
        } else {
            String kayitliSifre = stringList.get(0);
            String girilenSifre = new String(jPasswordField1.getPassword());
            
            if (girilenSifre.equals(kayitliSifre)) {
                logYaz("Başarılı Giriş");
                JOptionPane.showMessageDialog(this, "Giriş başarılı! Oyun açılıyor.");
                anaEkran.setVisible(true);
                this.dispose();
                
            } else {
                yanlisSayisi++;
                logYaz("Hatalı Giriş");
                
                if (yanlisSayisi >= 3) {
                    JOptionPane.showMessageDialog(this, "Şifrenizi 3 kere yanlış girdiniz! Program kapatılıyor.");
                    System.exit(0);
                } else {
                    JOptionPane.showMessageDialog(this, "Şifre yanlış!");
                }
            }
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Hata: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new SifreEkrani(null).setVisible(true));
        java.awt.EventQueue.invokeLater(() -> new P2Oyun());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
